// ...existing code from ../pages/StorePage.jsx...
// import StoreCard from "../components/StoreCard"; // If used, update to:
// import StoreCard from "../components/StoreCard";
// ...existing code...
